name: a-sharapov

networks:
  a-sharapov:
    driver: bridge

services:
  certbot:
    image: certbot/certbot:latest
    container_name: $CERTBOT_SERVICE_NAME
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: certbot certonly --webroot -w /var/www/certbot/ -d $MAIN_DOMAIN_NAME -d www.$MAIN_DOMAIN_NAME --agree-tos --email $MAIN_DOMAIN_EMAIL --no-eff-email
    environment:
      MAIN_DOMAIN_NAME: $MAIN_DOMAIN_NAME
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - proxy
    networks:
      - a-sharapov

  proxy:
    container_name: $NGINX_SERVICE_NAME
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/init.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/assets:/var/www/html/custom:rw
      - ./proxy/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    environment:
      WEB_SERVICE_NAME: $WEB_SERVICE_NAME
      WEB_SERVICE_PORT: $WEB_PORT
      DOMAIN_NAME: $MAIN_DOMAIN_NAME
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - a-sharapov
