version: '3.0'

networks:
  a-sharapov:
    driver: bridge

services:
  nginx:
    container_name: a-sharapov-proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    restart: on-failure
    networks:
      - a-sharapov
    volumes:
      - ./www-html:/var/www/html
      - ./certs:/etc/nginx/certs

  frontend:
    container_name: a-sharapov-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    command: npm run dev --host 0.0.0.0
    networks:
      - a-sharapov
    expose:
      - 3000
      - 24678
    ports:
      - "3000:3000"
      - "24678:24678"
    stdin_open: true
    restart: on-failure
  
  # certbot:
  #   image: certbot/certbot
  #   depemts_on:
  #     - nginx
  #   container_name: a-sharapov-certbot
  #   volumes:
  #     - ./certs:/etc/letsencrypt
  #     - www-html:/var/www/html
  #   command: certbot certonly --webroot --webroot-path=/var/www/html --email mail@a-sharapov.com --agree-tos --no-eff-email -d a-sharapov.com -d www.a-sharapov.com -d mail.a-sharapov.com

volumes:
  certs:
  www-html:
