# server {
#     listen 80;
#     listen [::]:80;

#     server_name a-sharapov.com

#     location ~/.well-known/acme-challenge {
#         allow all;
#         root /var/www/html;
#     }

#     location / {
#         rewrite ^ https://$host$request_uri? permanent;
#     }
# }

server {
    listen 80;
    #listen 443 default ssl http2;
    #listen [::]:443 default ssl http2;
    server_name localhost;
    server_tokens off;
    #ssl_certificate /etc/nginx/certs/live/a-sharapov.com/fullchain.pem;
    #ssl_certificate_key /etc/nginx/certs/live/a-sharapov.com/privatekey.pem;
    charset utf-8;

    # add_header X-Frame-Options "SAMEORIGIN" always;
    # add_header X-Content-Type-Options "nosniff" always;
    # add_header X-XSS-Protection "1; mode=block" always;
    # add_header Referrer-Policy "no-referrer-when-downgrade" always;
    # add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline';" always;

    # if ($scheme = http) {
    #     return 301 https://$server_name$request_uri;
    # }


    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}